- use-package.el
John, 
Please consider this patch.  I've added the ability to bind a key sequence to a package's keymap.  Package loading is deferred until that key sequence has been pressed, at which time the package is transparently loaded so that the next key pressed is routed into the package's keymap.  
Here's an example of its use:
```
(use-package ahg :bind-keymap ("C-c h g" . ahg-global-map))
```
> :bind-keymap - bind a key prefix to an autoloaded package keymap

- use-package.el
> Fix :ensure value interpretation

- README.md
add :defer n example to the README
> close #208

- use-package.el
Override argument no longer ignored.  Not adding keymap to list of
commands. `eval' no longer appears to be necessary, using direct
invocation of bind-key*.
> bind-keymap fixes.

- README.md
I'm also one of the new users who had small confusion with this section being at the top when I started using `use-package`.
Fixes #241.
> Move upgrading section to the bottom of README.

- use-package.el
e.g. `(use-package "isearch")` rather than `(use-package isearch)`
fixes #203, fixes #244.
Found 2 quoting mistakes in the [initial version][1]. I think it should work now.
[1]: https://github.com/npostavs/use-package/commit/ca16fd3b1fab4eb699825b510c1b35dbde9e58f6
> Re-add support for string package names

- README.md
- use-package.el
Hi.
I suggest a way to handle errors from packages loading process by overriding use-package handler
> error handling for use-package #246

- use-package.el
Fixes https://github.com/jwiegley/use-package/pull/284
Fix by @npostavs
> Install packages when byte-compiling (fix by @npostavs)

- use-package.el
I promise that I will not send PRs late at night
I promise that I will not send PRs late at night
I promise that I will not send PRs late at night
.... (times 100)
> Fix errant variable name.

- use-package.el
> Mark package as selected with package-install

- use-package.el
Also add require forms and group both under menu "Package".
> Add imenu support for use-package forms

- README.md
See Issue #384 -added some examples
> Added link to bind syntax and more :bind examples

- use-package.el
> Declare package-read-all-archive-contents

- use-package.el
This allows the user to customize the :ensure keyword by using a
different package manager than package.el.
> Add use-package-ensure-function

- use-package.el
Previously, the :config, :ensure, and :pin keywords had default
values (dependent on the values of the use-package-always-ensure and
use-package-always-pin). This change allows the user to customize the
default values used for those keywords, and add default values for
their own keywords in a non-hacky way.
This functionality would be useful for (as an example) the
quelpa-use-package package, which needs to use an advice to override
the functionality of :ensure. The same problem prevents adding a
use-package-always-quelpa variable in any reasonable way, without a
way to customize the default values of keywords.
> Add use-package-defaults

- use-package-tests.el
- use-package.el
Fixes #348, fixes #399. Fixes `use-package-tests.el`
> Handle :mode ("foo") better

- use-package.el
See https://github.com/jwiegley/use-package/pull/433#issuecomment-289317875
> Add use-package-always-defer-install

- use-package.el
This should address [this issue](https://github.com/jwiegley/use-package/pull/433#issuecomment-287606553).
> Fix :after keyword

- README.md
As a bit of an elisp newbie I liked this more complex example!
> More complex conditional example

- use-package.el
These keywords work equivalently to `:mode` or `:interpreter`, but for
`magic-mode-alist` and `magic-fallback-mode-alist`.
The handler function implementation is now passed a list to add to,
and shared by all four of them.
> Add `:magic` and `:magic-fallback` keywords (issue #469).

- README.md
- use-package.el
> Document :delight in the doc string and README.

- use-package.el
> Require Emacs version >= 24.3

- .gitignore
```
% make elc
% git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
bind-chord.elc
bind-key.elc
use-package-bind-key.elc
use-package-chords.elc
use-package-core.elc
use-package-delight.elc
use-package-diminish.elc
use-package-ensure-system-package.elc
use-package-ensure.elc
use-package-jump.elc
use-package.elc
```
> Add *.elc as git ignored files

- README.md
> Update README.md, melpa (stable) badges

- .travis.yml
Squashed and rebased version of https://github.com/jwiegley/use-package/pull/573
Minor edits made by me: Change emacs version to use for deploy to 25.3, and deploy
source branch to master as discussed on that PR thread.
> Travis hugo

- doc/setup-ox-hugo.el
Earlier we switched to http for Melpa because of this bug:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25061#90
That bug has now been fixed on emacs-26 branch.
That, and other consistency edits:
- Use default-directory instead of "."
- Comment refactoring
- "my/" prefix to "ox-hugo-" prefix
- Name the temp dir ox-hugo-site instead of ox-hugo-dev (the dev part
had got carried over from the ox-hugo project)
> Switch back to https Melpa for doc site related pkg installs

- README.md
- use-package-core.el
> Use a tabulated-list to display package configuration statistics

- use-package-core.el
Reverts jwiegley/use-package#645
> Revert "Fix report"

- default.mk
- use-package-core.el
This PR fixes both #650 and #644. The later has already been fixed by #645 but this was reverted in #646.
> Fix report again after revert

- README.md
- bind-key.el
> Document that remapping commands is supported with bind-key

- README.md
> Update debug info in readme

- use-package-bind-key.el
- use-package-chords.el
- use-package-core.el
- use-package-delight.el
- use-package-diminish.el
- use-package-ensure-system-package.el
- use-package-ensure.el
- use-package-jump.el
- use-package-lint.el
- use-package-tests.el
- use-package.el
This supercedes #617 and closes #648
> Enable lexical binding

- README.md
- use-package-ensure-system-package.el
closes https://github.com/jwiegley/use-package/issues/660
> allow :ensure-system-package to check the presence of files at path

- use-package-chords.el
per @tarsius’s comment
https://github.com/jwiegley/use-package/commit/042e7292e4c4b29be81f875c270bfaec40f75434#commitcomment-29996666
> prefix argument with _ to suppress Unused lexical argument warning

- README.md
SEE [#750](https://github.com/jwiegley/use-package/pull/750)
**NOTE :** my apologies for the double pull request.
> Fix documentation for defer

- use-package-core.el
> Clarify the documentation for :after

- README.md
- use-package-core.el
- use-package-tests.el
@wyuenho thank you for fixing the test code. I used your commit here and just updated the docs a little more.
> Fix tests and update documentation after #850

- .travis.yml
> Add emacs 26.3 and 27.1 to test matrix

- use-package-core.el
Currently the `use-package-report` columns have no sorters defined, which results in the Status, Last Event and the Time columns being sorted by lexicographical order. Furthermore, there's no default `tabulated-list-sort-key` defined, so by default the report is sorted by the order the `use-package` declarations were executed.
This PR proposes sorting the report by the **Time** column in descending order by default and default a sorter for each of the Status, Last Event and Time columns.
| Column     | Sorting Order                                                                      |
|------------|------------------------------------------------------------------------------------|
| Status     | `use-package` phase order                                                          |
| Last …
> Properly sort use-package-statistics-report

- use-package-core.el
If the variable has been customized, the `:set` function in this defcustom is not setting the default value when doing `M-x customize-group RET use-package RET` and throws an error, this PR fixes it.
```
Debugger entered--Lisp error: (void-variable use-package-enable-imenu-support)
custom-variable-modified-p((custom-variable :group (custom-group :documentation-shown t :custom-state unknown :tag "Use Package" :value use-package :buttons ((documentation-string :args nil :value "A use-package declaration for si..." :indent 0 :visibility-widget custom-visibility :parent #4 :doc-overlay #<overlay from 300 to 356 in *Customize Group: Use Package*> :buttons nil :from #<marker (moves after insertion) at 300 in *Customize Group: Use Package*> :to #<marker at 357 in *Customize Group: Use Package*>) …
```
> Fix void-variable use-package-enable-imenu-support

- use-package-core.el
> fix docstring. was: invalid function reference

- README.md
Change the MELPA badger link and the link in the installation section.
> Update MELPA links

- README.md
- use-package-tests.el
This commit follows suggestion at #696, #821.
> Add multiple and eval :custom-face usage

- .elpaignore
- bind-chord.el
- bind-key.el
- use-package-bind-key.el
- use-package-chords.el
- use-package-core.el
- use-package-delight.el
- use-package-diminish.el
- use-package-ensure-system-package.el
- use-package-ensure.el
- use-package-jump.el
- use-package-lint.el
- use-package.el
- use-package.org
1. Update copyright year
2. Set copyright to FSF
3. Add .elpaignore
> Prepare for submission to ELPA

- NEWS.md
- default.mk
- use-package-core.el
- use-package.el
- use-package.org
Bump patch version so ELPA can detect copyright year updates.
> Prepare for submission to GNU ELPA: Update version to 2.4.2

- .elpaignore
- NEWS.md
- bind-key.el
- default.mk
- doc/README.org
- use-package-core.el
- use-package.el
- use-package.org
- Add a README.org to explain basic purpose of the directory
- Add doc/* to .elpaignore
- Bump bind-key.el version so ELPA can detect any copyright year changes
- Bump use-package version so ELPA can detect new changes
> Prepare for GNU ELPA: more small changes

- bind-key.el
- use-package-bind-key.el
- use-package-chords-tests.el
- use-package-core.el
- use-package-ensure-system-package.el
- use-package-ensure.el
- use-package-jump.el
- use-package-lint.el
This fixes several stylistic documentation issues found using checkdoc.
More issues still remain to be fixed, I just did the low-hanging fruit here.
> Various checkdoc fixes

- README.md
- bind-chord.el
- bind-key.el
- use-package-bind-key.el
- use-package-tests.el
- use-package.texi
Reverts jwiegley/use-package#1019
> Revert "Allow multiple keymaps in :map argument"

- bind-key.el
- doclicense.texi
- docstyle.texi
- use-package-bind-key.el
- use-package-core.el
- use-package-delight.el
- use-package-diminish.el
- use-package-ensure-system-package.el
- use-package-ensure.el
- use-package-jump.el
- use-package-lint.el
- use-package-tests.el
- use-package.el
- use-package.texi
Hi John,
This just pulls in the latest changes from emacs.git. I don't imagine doing this every day, but I'm thinking that it might be a good idea to do this intermittently during the transition period until we archive this repository. The need for this will decrease once we can change use-package into a `:core` package.
What do you think?
> Merge changes from emacs.git
