use-package.el
In the macro `use-package-with-elapased-timer` use `bound-and-true-p`
go get the values of the customizable options `use-package-verbose`
and `use-package-minimum-reported-time`.  This way the library only
has to be required at compile time, provided these options are not
actually customized.  If the user has changed the values, then she
also has to load the library at runtime or the macros fall back to
the default of doing their job silently.  See #149.
=> Allow using expanded macro without loading feature

use-package.el
`*Messages*` contains
```
For information about GNU Emacs and the GNU system, type C-h C-a.
Failure in :init of bind-key: (wrong-type-argument sequencep 1)
use-package ok
```
`*Warnings*` buffer **pops up** with
```
Error (use-package): Failure in :init of bind-key: (wrong-type-argument sequencep 1)
```
`*Messages*` contains
```
For information about GNU Emacs and the GNU system, type C-h C-a.
use-package ok
```
---
Tested with `emacs -Q -L . -l ck.el`, where `ck.el` contains
```elisp
(require 'use-package)
(use-package bind-key
:init (progn (length 1) (message "bind-key ok")))
(use-package use-package
:init (message "use-package ok"))
```
=> use-package-expand: use display-warning

use-package.el
instead of name-string. This prevents triggering by config file names
that have the same name as the package.
Reprise of #53.
Fixes #167.
=> use--package: eval-after-load name

bind-key.el
instead of `"#<keymap>"`.
```
Key name          Command                                 Comments
----------------- --------------------------------------- ---------------------
C-x p             `#<keymap>'
projectile-rails-mode-goto-map
-------------------------------------------------------------------------------
m                 `projectile-rails-find-current-model'
```
```
Key name          Command                                 Comments
----------------- --------------------------------------- ---------------------
C-x p             `projectile-rails-mode-goto-map'
projectile-rails-mode-goto-map
-------------------------------------------------------------------------------
m                 `projectile-rails-find-current-model'
```
---
Tested with
```elisp
(require 'bind-key) …
```
=> get-binding-description: return keymap symbol

use-package.el
Hi John,
Started to use injected hooks in Spacemacs.
This PR fixes the nesting level of `run-hooks` sexps for injected `:init` and `:config` hooks. This is required to have `macroexpand-progn` correctly splice the passed expression.
Cheers,
syl20bnr
=> Fix calls to run-hooks for :init and :config injected hooks

use-package.el
solves #154  (which is closed).. 
I stole this snippet from Steve Purcell since I stumbled upon it when searching for something else...
https://github.com/purcell/emacs.d/blob/master/lisp/init-elpa.el#L48
=> Refresh package.el archives if package is missing.

use-package.el
We transform it into (:map foo (...) (...)) in the normalizer, and
no longer warn about unknown sorts of arg.
=> Support :bind (:map '(...)).

use-package.el
Emacs complained about `(void-variable name)` when package failed to load, now it properly loggs missing package to \*Messages\*
The error was introduced here: https://github.com/jwiegley/use-package/commit/a863840fe666e1ae71251d5515784890bf944376#diff-7d8cebd9ba9fff18a51d6ca83a396f34L895
=> fix quotation error

use-package.el
Since I'm going to create a small extension library that adds support for the `:chords` keyword, it would be helpful to re-use the existing `use-package-handler/:bind` method. This allows the macro to be used in the handler to be passed in as an argument to allow for this in an external package.
related to #258
=> Pass in symbol of bind macro, for more extensible re-use of same handler

use-package.el
Turned out to be relatively simple. I like the reworked code base!
After provides `eval-after-load' functionality for any number of
features. This helps to avoid deeply nested `use-package' statements.
Closes #274
=> Support for after keyword.

use-package.el
**Description:**
Currently `:ensure` option is executed during macro expansion time.
This results in issues like:
https://github.com/jwiegley/use-package/issues/260 and https://github.com/company-mode/company-mode/issues/387
**Issue:**
If you have `company-mode` installed, `use-package` installed and `use-package-always-ensure` set to `t`, then typing `(use-package 123|` will make `company-mode` macro-expand `use-package` macro which will trigger contacting package repositories and fetching `123` package.
**Solution:**
This pull request moves execution of `:ensure` option from macro expansion time to runtime.
**WARNING**
**Please, double-check and test everything!**
Macros are tricky things, I might forgot to add a backquote or something.
I have tested several cases locally and for me it …
=> Move :ensure option execution from macro expansion phase to runtime phase

use-package.el
Fix (but I'm not sure) for #299
Changes:
1) move `:pin` option out of macro-expansion phase 
(the same thing we did for the `:ensure` option)
2) fix order of `:pin` and `:ensure` options.
`use-package-sort-keywords` function works correctly and puts `:pin` before `:ensure` after sorting.
But, after macro-expansion `:pin`'s body appears after the `:ensure`s body.
So, it pins the package, but after the installation (which is obviously wrong).
3) replace 
`(push (cons package archive-name) package-pinned-packages)` 
with 
`(add-to-list 'package-pinned-packages (cons package archive-name) t)`
Because `push` doesn't check if entry is already a member of a list. 
Hence, if you have something like `(use-package test :pin melpa)` and eval that form N times, you will get N '(test . "melpa")` …
=> Move :pin out of macro expansion phase

README.md, use-package.el
`use-package-always-pin' allows a default archive (or manual) to be
specified for all use-package statements, unless explicitly overridden.
I finally got irritated with wanted to stay on stable packages but finding one package has to be installed from MELPA.
=> Add new option `-always-pin'

README.md, use-package.el
In #302 @adouzzy mentioned that using lots of `:pin` makes startup time very long.
Even main page says:
>NOTE: if you pin a lot of packages, it will be slightly slower to start Emacs compared to manually adding all packages to the package-pinned-packages variable. However, should you do it this way, you need to keep track of when (package-initialize) is called, so letting use-package handle it for you is arguably worth the cost.
I noticed that in `use-package-pin-package` function we always call `(package-initialize t)`.
(I don't know though if it's done for purpose or not. If yes, then ignore this pull request)
For some reasons, `package-initialize` does not check if `package` has already been initialized.
That function loads all descriptors and reads all archive contents.
Obviously, …
=> Do not package-initialize on each :pin

use-package.el
Also shutup bytecompiler about package-archive-contents.
* use-package.el (use-package-ensure-elpa): Add package to selected package
by using second arg of package install.
=> When :ensure is used install package as a selected package.

bind-key.el
A number of Cs corresponding to Ctrl have been lower cased in comments in cd65aebaa.
=> Upper casing Cs corresponding to Ctrl

use-package.el
It is possible with `bind-key` and `define-key` (and also `bind-chord`
and `key-chord-define`) to define a binding to a string's value, i.e:
``` elisp
(bind-key "C-;" "the ")
(bind-chord "^^" "λ")
```
This adds an option for `(use-package-normalize-pairs)` that allows
string values to be given with the `:bind` (and also `:chord`) keywords
to expand into these definitions.
=> Allow string values in cons for :bind keywords

bind-key.el
Currently there may be issues if a keymap contains an improper
documentation and `bind-key-describe-special-forms` is set to `t`.
- Example 1
Bind "M-o" (which is bound to `facemenu-keymap` by default) to anything:
```elisp
(bind-key "M-o" 'backward-word)
```
Now `M-x describe-personal-keybindings` gives an error:
Wrong type argument: stringp, 2283076
This happens because `(get-binding-description 'facemenu-keymap)`
evaluates to 2283076.
- Example 2
Make an undocumented map:
```elisp
(bind-keys
:prefix-map dummy-map
:prefix "M-z"
("b" . backward-char)
("f" . forward-char))
```
Now `M-x describe-personal-keybindings` gives a not-very-useful `nil`:
M-z               `nil'                                   was `zap-to-char'
So what about some modification in `get-binding-description` …
=> Handle the case when keymap has a broken documentation

bind-key.el
bind-key.el (bind-keys*): `override-global-map` needs to be quoted so
the symbol is passed to `bind-keys-form` and not the value.
Fixes #323.
(Emacs CA already signed, if you should need it; though this is so small, I don't expect it to be a problem.)
=> Quote variable in bind-keys*

use-package.el
To load some related packages as order using :after.
```lisp
(use-package multi-web-mode
:after web-mode
:config
(message "both web-mode and multi-web-mode are available"))
```
However, when web-mode is installed and multi-web-mode is not installed, this error occurred.
> (file-error "Cannot open load file" "no such file or directory" "multi-web-mode")
=> Fix to ignore load error caused via :after

use-package.el
lisp-mode-symbol-regexp was not defined in Emacs 24.5.
=> Fix imenu support for older versions

use-package.el
The docstring of use-package says that :init should run before the
package is loaded but using :after moves the require statement ahead of
:init when any package specified in :after is already loaded. In the
following example, in the first case bar-x might get set before or after
bar is loaded depending on if foo is already loaded at the time, while
the second case always sets bar-x first.
(use-package bar
:after (foo)
:init (setq bar-x 2)
:config (bar-mode))
(use-package bar
:init (setq bar-x 2)
:config (bar-mode))
This commit fixes the issue and makes sure that bar-x is set before bar
is loaded by use-package. Fixes #352.
=> Move :init forms before :after and :demand

use-package.el
fixes #341.
```
Don't pass a constant as the state
for use-package-process-keywords, because the function may modify the
list object.  Modifying a quoted constant can lead to unexpected side
effects (e.g. values from previous use-package forms end up in
subsequent ones).
```
---
UPDATE: added a rebase of #253, and a fix for the `declare-function` expression.
=> Some minor fixes

use-package.el
Add a boundp guard to package-pinned-packages before referencing it in
use-package-ensure-elpa.
I'm just duplicating the boundp guard from use-package-pin-package. Let me know if you prefer another approach.
I've tested this on Ubuntu 14.04 and verified it no longer throws an error, but haven't tested much else. Specifically, I don't really use the :pin feature myself, and haven't actually tested to ensure that package pinning works as expected.
Fixes #375
=> Ensure package-pinned-packages is bound before referencing it.

README.md
```
Using tex-site doesn't work with :defer as tex-site is automatically
loaded when the package is initialized.
```
Closes #379.
=> Use tex instead of tex-site for AUCTeX

bind-key.el
```
Just because a keymap variable is bound at macro-expansion-time
doesn't mean that it must be bound at run-time too.
Change `bind-keys-form', which is used by `bind-keys' and other
macros, to return a form which delays the decision on whether to
wrap the binding forms with `eval-after-load' until run-time.
```
Fixes #378.
=> Delay decision whether to use eval-after-load until run-time

bind-key.el, use-package.el
```
In "use-package.el" prefix headings with ";;;" instead of just
";;".  In "bind-key.el" add the missing ";;; Code:" heading.
In both libraries set `outline-regexp' to an appropriate value.
```
=> Support outline-minor-mode

use-package.el
The `README` describes the `:preface` keyword as occurring before everything but `:disabled`, yet the former is currently preceded by seven other keywords in addition to the latter.
Most importantly, `:preface` occurs after `:ensure` and the three conditional keywords, thus reducing its use for establishing definitions.
=> Increase :preface priority

use-package.el
This pull request is a continuation from https://github.com/jwiegley/use-package/pull/426#issuecomment-279479609 in response to #428 and #429, which it should fix.
The problem was indeed that I didn't quite replicate the exact logic of the original version. In the original version, for each keyword, `use-package-plist-maybe-put` was only called if the relevant predicate returned true, whereas `use-package-sort-keywords` was called unconditionally. In the new version, `use-package-sort-keywords` was also called only when the relevant predicate returned true.
=> Fix use-package-defaults

README.md
Since the value after `disabled:` is ignored
Fixes #387
=> Readme: Remove t from example usage of disabled:

use-package.el
Instead of using defvar for lisp-mode-symbol-regexp, wait until
lisp-mode is loaded and check for its existence to avoid making
use-package the place where this variable is declared.
By the way, sorry for all of the changes. I wasn't thinking carefully when I did this the first time.
=> Improve imenu support

use-package.el
This is an attempt at resolving #329. The new interactive function
use-package-jump-to-package-form will prompt with a completing read of
all known packages. After selecting a package, use-package-find-require
searches load-history to see where the package was required and then I
attempt to find the correct use-package form using
use-package-form-regexp.
It will fail if the use-package form you are looking for did not
actually load the package. For example it could be something that is a
dependency of a library that was already loaded. In some sense this is a
feature because it is helpful to know that the library was already
loaded when your use-package form was encountered. It will also fail if
your use-package declaration doesn't match the regexp used, but this is
easily adjusted.
=> Add function use-package-jump-to-package-form

use-package.el
First cut at :defer-install keyword
This new keyword, if provided along with a non-nil value, causes the action
of :ensure to be deferred until "necessary". Package installation can be
triggered by the user calling the new interactive function
`use-package-install-deferred-package', or by the feature declared by the
`use-package' form being required. This latter behavior seems to be the
simplest way to make sure that package installation actually takes place
when it needs to, but it requires that an advice be added to `require',
which may be considered overly intrusive. (Also, it's generally considered
bad practice for functions in Emacs to put advice on other functions in
Emacs.) Thus it may make sense to add an option or function to explicitly
enable this behavior, if there does not …
=> [RFC] Support for deferred installation

use-package.el
The parsing logic in `use-package-normalize-pairs` is not designed to
deal with keyword arguments. However, `use-package-normalize-pairs` is
used to process the arguments to :bind, which can include keyword
arguments. These keyword arguments are supposed to be passed untouched
to the underlying `bind-keys` function, but there is a clause in
`use-package-normalize-pairs` that replaces lists with their first
element. Thus an invocation like:
```
(use-package company
:bind (:map company-active-map
:filter (company-explicit-action-p)
("RET" . company-complete-selection)))
```
Generates code like this:
```
(bind-keys
:map company-active-map
:filter company-explicit-action-p
("RET" . company-complete-selection))
```
Which generates an error since `company-explicit-action-p` is now
being …
=> Don't mutilate keyword arguments in :bind

use-package.el
The previous version of `use-package-normalize-value`, when passed
nil, would return the list `(symbol-value (quote nil))`. This meant that
keywords which used `use-package-normalize-value` or the higher-level
normalizer `use-package-normalize-test` would get a non-nil
argument (i.e. the above list) even when the user specified nil to the
package.
This had the concrete impact of making it so that `:defer-install nil`
was treated as `:defer-install t`.
See https://github.com/jwiegley/use-package/pull/443#issuecomment-291745802.
=> Make use-package-normalize-value handle nil better

README.md
Modification of @keithmantell's #451
This is what exec-path-from-shell recommends to run it conditionally. Unlike system-type, window-system is set to nil in terminals, preventing unnecessarily loading exec-path-from-shell (see https://github.com/purcell/exec-path-from-shell/pull/53#issuecomment-293078491).
=> Use recommended exec-path-from-shell predicate

use-package.el
Just a minor error. I was doing something silly with my deferred installation, and triggered this (probably rare) case in the logic. Unfortunately, the error `void-variable command` prevented `use-package` from giving me a nice error message saying so.
=> Fix quoting error in failed autoload message

.travis.yml, README.md
While `use-package`'s test suite is currently limited in scope, I think it would be helpful to run it on a continuous integration service like Travis to encourage testing in new contributions.
If you would like to merge this, please enable Travis first by visiting [your profile](https://travis-ci.org/profile) and toggling `use-package`. Note that this uses a snapshot PPA to install Emacs, you'd need something fancier if you want to test against multiple Emacs versions or older versions. The test command just runs ERT in batch mode, but it would need to be updated if the source or test file lists are changed.
=> Use Travis CI

use-package.el
If the network is missing and there is a new use-package with :ensure,
startup would fail part of the way through due package.el being unable
to reach the package repo.  This will catch that error and report it
while allowing startup to continue.
Discovered and fixed on an airplane.  :)
=> Protect against errors during package install

.travis.yml
Container builds on Travis generally start faster. I also replaced `ppa:ubuntu-elisp`'s `emacs-snapshot` with Ubuntu Trusty's official `emacs` package (version 24.3), since the container builds don't support that custom PPA.
=> Use Travis' container environment for improved performance

use-package.el
Previously, deferred installation didn't work because I didn't convert the result of a `completing-read` back from a string to a symbol, which meant the hash-table lookup failed.
=> Fix bug in use-package-install-deferred-package

use-package.el
It expects a literal string as argument at macro-expansion time, but we need to construct the message.
The second commit makes some cosmetic changes to that function, one of which makes a potential issue more visible.
The first clause ends with an explicit `t` implying that the return value is relevant, but the second does not. It is possible that its last form sometimes returns `nil` and sometimes non-nil and that relying on that value is the appropriate thing to do here. I did not check, but it is quite possible that the return value has to be set explicitly in the second clause too. Or maybe the return value does not matter at all and the explicit `t` in the first clause should be removed.
=> Don't use with-demoted-errors in use-package-ensure-elpa 

README.md, use-package.el
One in the readme, two in the docstrings in use-package.el
=> Fix documentation typos

README.md, use-package.el
Hello,
This PR adds two new keyword: `:customize` and `:custom-faces`. These are shortcuts to cleanup calls to `customize-set-variable` and `custom-set-faces'`in the `:config` part. I do not use the Emacs internal save to custom.el setup because it's not easy to track in version control. I prefer to keep my package configuration in one place and these two keywords make this easier.
``` elisp
(use-package comint
:customize
(comint-buffer-maximum-size 20000 "Increase comint buffer size.")
(comint-prompt-read-only t "Make the prompt read only."))
(use-package eruby-mode
:custom-faces
(eruby-standard-face ((t (:slant italic)))))
```
The comments are not mandatory for the `:customize` keyword.
I don't know if you would be willing to add these kind of keywords, so this PR is more about asking …
=> Add customization keywords

use-package-tests.el, use-package.el
When given no arguments, have :diminish assume it should diminish a
mode named after the current package (the package’s name, with “-mode”
appended, if it’s not already) to an empty string.
When given only a string to diminish an implicit package name to, do
not append “-mode” to the package name if it already ends with
it.  (This is a backwards-incompatible change if someone was
diminishing a package named “foo-mode” implementing `foo-mode-mode`.)
Add test cases for `use-package-normalize-diminish`.
This addresses some of the redundancy mentioned in issue #288.
=> Allow `:diminish` with no arguments.

use-package-core.el
Previously, `M-x use-package` would give `use-package-normalize/:disabled` as a completion candidate which seemed a little odd to me.
=> Fix function accidentally made interactive

doc/setup-ox-hugo.el, doc/themes/hugo-alabaster-theme/layouts/partials/footer.html, use-package.org
- Update the source link of the Org file in the site footer.
- Fix the Org macro link-jump for hugo exports
- Remove unrelated stuff from setup-ox-hugo.el (carry-forward from
ox-hugo repo)
=> Minor fixes with use-package doc site

.travis.yml, doc/setup-ox-hugo.el
Emacs 26 ships with Org 9.1.x. So use that to build the doc site, as
then there won't be the need to install Org 9.x from Org Elpa.
This speeds up the doc site deployment by about a minute.
=> Use emacs 26 to build the doc site

.travis.yml
The order of the emacs versions in the matrix is changed so that the CI job with emacs 26 runs first.
The doc site is generated using emacs 26, and so the doc site will be updated first. 
Other emacs versions are ordered so that the newer versions are tested first and then the older.
The master version of emacs is still kept at the last.
=> Move EMACS_VERSION=26 to the top so that the docs build first

doc/setup-ox-hugo.el
- Set a common prefix for all vars and functions in setup-ox-hugo.el
- Auto-set ox-hugo-install-org-from-elpa based on the emacs version (installs Org from Elpa if emacs 25.x and older).
- Use http for Melpa, otherwise fails installing ox-hugo.. probably because Travis env lacks gnutls dependency?
- Installing toc-org is not needed at the moment, so commenting that out
=> Cleanup setup ox hugo

README.md
Some elisp examples were not properly higlighted.
=> Fix some code hilighting

use-package-core.el
Instead of testing the lenght of each form passed to `:custom-face`,
the sanity check would test the number of forms passed to `:custom-face`,
causing it to fail when more than 2 face customisations are used.
Fixes #600.
=> Fix sanity check for correct :custom-face format

README.md, use-package-core.el
I noticed that the "Gathering Statistics" instructions for rendering the Org
table could be automated for convenience. Now the table is reformatted
automatically, and you can still manually sort it. I'm not sorting it by default
to maintain the same order of use-package forms for easier troubleshooting.
=> Render the use-package-report table using Org

use-package-core.el
The function `elisp--local-variables` inserts this unbound variable into macro
forms to determine the locally bound variables for
`elisp-completion-at-point`. It ends up throwing a lot of errors since it's not
a keyword. Deleting it doesn't seem to break anything with completion, so ignore
it for now.
Related to https://github.com/abo-abo/hydra/commit/b12d37ac00d4f677b7684ed1af7d04d996167dbb
=> Handle automatic macro expansion by elisp-completion-at-point

use-package-core.el
org-table-align is an autoloaded function so the byte compiler can
find it. orgtbl-ctrl-c-ctrl-c isn't so we get a warning about
undefined functions.
=> Prefer org-table-align to orgtbl-ctrl-c-ctrl-c

use-package-bind-key.el, use-package-chords.el, use-package-core.el, use-package-delight.el, use-package-diminish.el, use-package-ensure.el, use-package-jump.el, use-package-lint.el, use-package-tests.el, use-package.el
Using this reduces my Emacs load time a bit --- down from about 2.5 seconds to about 2.2 seconds. 
But some tests are failing at the moment. I think it's because lambdas get returned as closures, but I'll have to look later.
=> [WIP] Lexical bindings

.travis.yml
The site is published in <REPO ROOT>/doc/public. But for some reason,
the local_dir value of "public" worked earlier.
Some change in Travis in the last ~18 days now causes failure with
that exact same .travis.yml.
But changing the "local_dir" value from "public" to "doc/public" fixes
the issue.
=> Change the local_dir value to match some upstream Travis change

doc/Makefile, doc/static/css/style.css
ox-hugo now has a feature that the Org OPTIONS "num" gets respected. 
The use-package.org has this line:
#+OPTIONS: H:4 num:3 toc:2 creator:t
So it makes sense to have section numbers in the Info manual, but probably not so much on the site.
An elegant way is to allow the section numbers be exported for the site too.. but simply hide them in CSS.
Also update Hugo version to 0.34
=> Don't display section numbers in doc site

use-package-core.el
This option allows use-package to skip over keywords it doesn't recognize.
The reason I want this option is that some keywords I use are tied to certain
packages being loaded, and I don't want a large chunk of my init file to fail if
any of those packages don't load.
=> Add use-package-ignore-unknown-keywords option

use-package-core.el
Previously the argument was never used.
=> Fix usage of plist argument in use-package-normalize-plist

use-package-bind-key.el
bind-key supports the keyword ":package" but use-package does not know that. Adding this should be helpful. In the future, maybe we could automatically fill in with the use-package package, but that could be a breaking change.
=> Support ":package" in use-package

use-package.org, use-package.texi
use-package is one of the most popular emacs packages, so it's better to encourage safer installation practices than plain `http://`. I hope I didn't miss anything.
P.S. Cheers @jwiegley, thanks for your awesome work!
=> Encourage installation via https instead of http

README.md, use-package-ensure-system-package.el
closes https://github.com/jwiegley/use-package/issues/652
=> :ensure-system-package - allow cdr of cons to be a package name symbol

use-package-ensure-system-package.el
The function introduced in #673 wasn't declared at compile time, and
it made byte compiler unhappy. Moreover, it was forgotten to remove
redundant compile time variables. Thanks @tarsius for pointing that
out.
This change
* Removes redundant variable declarations
* Adds `system-packages-get-command` function declaration.
=> ensure-system-package cleanup

use-package-chords.el
When it is at the end, the keys don't get bound until after the package has been loaded, because it comes after :defer, which is bad.  Placing it at the beginning allows the key bindings to be mapped to auto-loaded functions before the package is loaded, so that a key chord press triggers the package load.
=> Place :chords at beginning of use-package-keywords

use-package-bind-key.el
By adding events of the form (cons t event) to unread-command-events, Emacs
correctly updates this-command-keys for the subsequent use of the prefix.
Before this change, packages like my which-key were not getting the correct
prefix after use-package-autoload-keymap loaded the relevant package.
See https://github.com/justbur/emacs-which-key/issues/192
=> Correct prefix keys after use-package-autoload-keymap

README.md, use-package-ensure-system-package.el
:ensure-system-package was installing packages by running
system-packages-get-command via async-shell-command. This meant that
system-packages-use-sudo wasn't being honoured.
This patch makes :ensure-system-package use system-packages-install
for all cases, except where a custom install command is supplied, in
which case async-shell-command is used.
This issue was introduced in 7303e89a8343fc7 [#673], as a fix for
[#661]. Prior to that commit, system-packages-use-sudo was being
honoured.
This patch also fixes a bug where a cons containing a lone symbol in a
list of conses causes nil to used as the package to install.
=> [Fix #720] Install system packages using system-packages-install

README.md
In many tutorials, one of the first features of `use-package` mentioned after its use is introduced is its ability to call package managers. Here's three examples from three different tutorials:
> With it [`use-package`], I can automatically download and install other packages from the emacs package databases when it detects they're missing.
> ```
> (use-package smex
>  :ensure t
>  :bind (("M-x" . smex))
>  :config (smex-initialize))
> ```
> And now Emacs ensures the package is installed [...]
> ```
> (use-package general :ensure t)
> ```
> It should check for the general package and make sure it is accessible. If not, the :ensure t part of the previous chunks tells use-package to download it [...]
While this focus on downloading packages is understandable, as it is one of the most …
=> Add comparison to package managers

use-package-core.el
Emacs 25 defined a global variable `features`, which triggers a
warning "Lexical argument shadows the dynamic variable features".
That's not `use-package`'s fault, but we should suppress the warning
anyway, so that there is no additional noise that would cause us to
potentially overlook warnings that absolutely have to be addressed.
=> Silence byte-compiler on Emacs 25

README.md
In an attempt to clarify documentation.
=> Mention that :hook implies :defer in defer section

README.md
Without requiring `use-package-ensure`, setting `use-package-always-ensure` did not actually work for me.
=> Mention use-package-ensure in README

README.md
This may seem trivial, but these few typographical changes will make it easier for users to read the README.
=> Fix typo for notes in README

README.md
Without using the `no-query` option, when you install [pdf-tools](https://github.com/politza/pdf-tools), it will send you a dialog message (y/n) to proceed with the installation, which we want to avoid most of the time because it prevents the automatic installation of your packages.
**SEE**: [this issue](https://github.com/politza/pdf-tools/issues/312)
=> Add no-query option for pdf-tools-install

use-package-core.el, use-package-tests.el
Fix #696.
Use `backquote` instead of `quote`.
=> Make custom-face evaluate elisp.

use-package-core.el, use-package-tests.el
I would like to propose the following change to `use-package`: when byte-compiling, use `require` to load packages, rather than `load`. This means that packages are not loaded twice, which is slow and can sometimes break things if the user's configuration overrides something that was defined in a package.
=> Use `require', not `load', when byte-compiling

README.md
I struggled quite a bit with hooks as for strange reasons they sometimes didn't work. It's only when I understood there was a `use-package-hook-name-suffix` variable that it dawned on me what was happening. So here my attempt to clarify the situation.
=> Attempt to explain omit "-hook" better

use-package-core.el
Solves https://github.com/jwiegley/use-package/issues/842
=> typo, should be a vector, not a bytecode object

use-package-core.el, use-package-tests.el
Fixes #785 
I couldn't figure out what the special `(t)` value is for `:config`, so I left that in even though it seems to have identical effect to `nil`.
=> Call hooks even if no config

use-package-core.el
This was discussed in #517 and I CC-ed @jwiegley on the emacs-devel discussion.
The change will ensure that `:custom` vars are not also saved to custom.el.
In my testing it worked correctly, I don't see custom.el entries for those variables anymore. Testing is welcome!
=> use-package-core.el: use the Emacs set-default function to avoid saving :custom vars twice

bind-key.el, use-package-tests.el
Sometimes, there are packages such as [prettier](https://github.com/jscheid/prettier.el) that expose commands that one would like to bind to multiple modes in their mode hooks. In which case the mode map will likely be dynamically constructed from the mode symbol, and one would like to bind keys like the following:
```elisp
(dolist (mode '(css-mode js-mode ...))
(let ((mode-hook (derived-mode-hook-name mode)))
(add-hook mode-hook (lambda ()
(bind-key "C-c f" 'prettier-prettify (derived-mode-map-name mode)))))
```
The problem is,  `bind-key` currently does not support `KEYMAP` supplied as a symbol, and if it is supplied as a `(symbol-value (derived-mode-map-name mode))`, there's no way to reverse lookup the name of the variable from the symbol value later on when constructing the buffer …
=> Support keymap symbol in bind-key. Fix #845

use-package-core.el, use-package-tests.el
This attempts to resolve #861 and #856 after #850 was merged as follows:
* revert to old `customize-set-variable` call instead of `set-default`
* add a synthetic theme property that's enough to prevent the customized variable from getting saved, which was the original goal of #850 
* the synthetic theme property is not enough to add the customized variable to the `custom-set-faces` portion of the customize save file
* this follows advice from @link0ff and @evelineraine and others in the above referenced PRs and bug reports for which I'm very grateful
* this should restore the minor-mode custom set behavior
* tests may need fixing
=> Preserve comment and set synthetic theme

use-package-core.el
* eval-when-compile for cases where use-package is only required at
compile time
* remove the 'use-package theme from custom-enabled-themes so e.g.
(mapc #'disable-theme custom-enabled-themes)
won't kill user settings.
=> Remove use-package theme from global list of custom-enabled-themes

use-package-core.el
This is a small optimization for #881 / #899 (FYI @tzz). With the current `master` the following
```elisp
(use-package recentf
:demand t
:custom
(recentf-max-saved-items 1000)
(recentf-max-menu-items 500)
(recentf-auto-cleanup (* 5 60))
(recentf-mode t))
```
expands to
```elisp
(progn
(let
((custom--inhibit-theme-enable nil))
(custom-theme-set-variables 'use-package
'(recentf-max-saved-items 1000 nil nil "Customized with use-package recentf")))
(let
((custom--inhibit-theme-enable nil))
(custom-theme-set-variables 'use-package
'(recentf-max-menu-items 500 nil nil "Customized with use-package recentf")))
(let
((custom--inhibit-theme-enable nil))
(custom-theme-set-variables 'use-package
'(recentf-auto-cleanup
(* 5 60)
nil nil "Customized with use-package recentf")))
(let …
```
=> Use a single let binding when expanding consecutive :custom forms

use-package-core.el, use-package-tests.el
Addresses #902 
* new defcustom `use-package-use-theme` to disable themes
* define the synthetic theme every time it might be needed to avoid issues reported in #902
=> Add use-package-use-theme and avoid missing theme errors

bind-key.el
=> Improved unbind-key which really removes the keys

use-package-core.el
This fixes a typo where the `use-package` docstring refers to a non-existent function.
=> Fix typo in use-package docstring

Makefile.doc
It seems like `org-man.el` has been renamed to `ol-man.el` in commit
[453c79a6193d66add56062f2a9788cadff509f7d](https://git.sr.ht/~bzg/org-contrib/commit/453c79a6193d66add56062f2a9788cadff509f7d)
of [org-contrib](https://git.sr.ht/~bzg/org-contrib).
Fixes #980.
=> Makefile.doc: Rename org-man to ol-man

bind-key.el
Back in Emacs-21.1, `define-minor-mode` grew keyword arguments to
replace its old positional arguments.  Starting with Emacs-28.1
a warning will be omitted if positional arguments are still used.
=> Avoid positional arguments to define-minor-mode

README.md, bind-key.el, use-package-bind-key.el
Add keywords to generate and bind keys in repeat maps, for use with emacs' new `repeat-mode`. Heavily inspired by the syntax of [define-repeat-map.el](https://tildegit.org/acdw/define-repeat-map.el). Fix #964.
It's worth mentioning that I tried to implement an `:enter` keyword as well, which would set the `repeat-map` property of a command, but without binding that command in the keymap. But I discovered that commands like this (with a `repeat-map` property pointing at a keymap in which they are not themselves bound) don't seem to actually invoke the repeat map. I tried it with the standard, manual way of building a repeat map and that didn't work either, so I think this is a bug with repeat-mode (or a feature which I don't understand). `:enter` would probably be the rarest used keyword …
=> Bind keys repeat map

README.md
The code binds keys to helm-command-map and the description says helm-mode-map.  Should they should be the same map name?
=> Consistency in description of :map

.github/workflows/test.yml
Add GitHub Actions config yaml.
This PR is just introduce GitHub Actions config yaml for test CI.
There're no doc jobs, so there're more work to move GitHub
Actions completely.
=> Add GitHub Actions config yaml

doc/setup-ox-hugo.el
In case ox-hugo is not present, requiring the file won't throw an error.
The motivation for this change is that emacs-ng (https://github.com/emacs-ng/emacs-ng/issues/98) wants to bundle some packages by default that are not (yet?) in default GNUEmacs.
Using submodules is what feels easiest, but that `require` makes the build fail. When use-package will be part of emacs this won't be needed, but if we get this merged, we can get a headstart there.
I've my FSF papers signed and on file :+1: (for 1 line it probably doesn't matter, but anyway)
=> require ox-hugo doesn't error if not found

bind-key.el
to boost startup performance, it is better to avoid invoking
`read-kbd-macro` at run time which requires 'cl-lib.
it takes ~20ms to load cl-lib
=> optimization: constant folding for read-kbd-macro

use-package-core.el
I noticed that I often add a special setup function or lambda to the mode hooks in use-package. Like in the example config of evil-org.
```
(use-package evil-org
:after (evil org)
:hook (org-mode-hook . evil-org-mode)
:config
(add-hook 'evil-org-mode-hook
(lambda ()
(evil-org-set-key-theme)))
(require 'evil-org-agenda)
(evil-org-agenda-set-keys))
```
I wanted to get rid of this `add-hook` line and came up with the `:local` keyword
```
(use-package evil-org
:after (evil org)
:hook (org-mode-hook . evil-org-mode)
:config
(require 'evil-org-agenda)
(evil-org-agenda-set-keys)
:local
(evil-org-set-key-theme)
```
In this case it is guessed that the hook is `evil-org-mode-hook`.
This keyword also supports the definition of multiple hooks e.g.
```
(use-package cc-mode
:config
(setq-default …
```
=> ':local' keyword adding code to mode-hook

bind-chord.el, use-package-chords-tests.el, use-package-chords.el
Also improve :chord keyword syntax processing to more closely mimic bind-keys since the same binding normalizer function is used.
Also add tests for use-package-chords to cover these test cases.
Update homepage url and version for both `bind-chord` and `use-package-chords`.
Closes #777.
=> Update bind-chords to use eval-after-load when keymaps are declared but not bound

use-package-core.el
This function extraction 1) makes the code slightly more understandable and 2) allows for tinkerers like me to override the way mode symbols are passed into the `:hook` keyword hook generation.
For example, it lets me accomplish what I was looking for in #612 with the following:
```
(defun my-use-package-hook-handler-normalize-mode-symbols (syms)
(if (use-package-non-nil-symbolp syms)
(condition-case _err
(symbol-value syms)
(error
(list syms)))
syms))
(advice-add 'use-package-hook-handler-normalize-mode-symbols :override
#'my-use-package-hook-handler-normalize-mode-symbols)
(defconst my-writing-modes '(org-mode markdown-mode fountain-mode git-commit-mode))
(use-package face-remap
:hook
(my-writing-modes . variable-pitch-mode))
```
=> extract use-package-hook-handler-normalize-mode-symbols function

use-package-ensure-system-package.el
re-submission of #744 off a feature branch
--
This makes the syntax options consistent with other `use-package`
keywords. Both of these are now valid:
```
(use-package format-all
:ensure-system-package
(prettier . "npm i -g prettier")
(rufo . "gem install rufo"))
(use-package format-all
:ensure-system-package
((prettier . "npm i -g prettier")
(rufo . "gem install rufo")))
```
=> use `use-package-as-one` for normalizing `:ensure-system-package`

use-package-core.el
Hi!
`use-pacakge` specified lisp-indent-function to indent like `defun`.
Currently, use-package main macro specify indent as `(declare (indent 1))`,
then change indent mode like `defun`.
`(declare (indent defun))` is same effect. It is simple and useful when redefining it when debug.
---
- Current
1.1. When eval `use-package` loaded.
```
(get 'use-package 'lisp-indent-function)
;; => defun
```
1.2. Then redefine `use-package`, and eval below. (indent broken while this value)
```
(get 'use-package 'lisp-indent-function)
;; => 1
```
1.3. Eval `(put 'use-package 'lisp-indent-function 'defun)` and eval below. (indent issue fixed)
```
(get 'use-package 'lisp-indent-function)
;; => defun
```
- Changed
2.1. When eval `use-package` loaded.
```
(get 'use-package 'lisp-indent-function)
;; => defun …
```
=> Fix declare style

.gitignore, Makefile, Makefile.doc, default.mk, use-package.org, use-package.texi
I originally added the manual and just had another look.  There was a lot of cruft laying around and I removed that.
The texi file also had not been regenerated in a while.
Due to the cleanup it should now be possible for everyone to update the texi file by running `make texi` or if the intention is to amend to the current head commit, then `AMEND=t make texi`.
=> Cleanup manual and regenerate use-package.texi

bind-key.el, use-package-core.el, use-package-ensure.el
The byte-compiler started pointing this out:
Warning: docstring has wrong usage of unescaped single
quotes (use \= or different quoting)
=> Quote single quotes in docstrings or use different quoting

bind-key.el
In cb90d3f the arguments to `define-minor-mode` were changed
erroneously. Whereas the `override-global-mode` was initially defined
as `(define-minor-mode override-global-mode "..." t "")`, the two
latter arguments where changed to `:global t :lighter ""`. However,
the two original arguments corresponded to the keywords `:init-value`
and `:lighter`, respectively.
With `:init-value t` missing, the minor mode isn't enabled by default,
and `bind-key*` appears not to work (see also #991). This fixes the
issue.
Note that to follow the exact meaning of the original code, one would
also have to remove the `:global t` argument. I don't know if that's
desirable or not, probably not.
=> Make sure that bind-key's `override-global-mode` is initially on

use-package-core.el
I don't know how long `use-package` plans on supporting older versions of Emacs, or if it's alright to remove some minimal features supporting those versions (<=25), but it would be really nice to remove the font-lock keywords it adds. These are already highlighted on Emacs 26+ and shouldn't be needed on these versions. Additionally, this should not break anything other than font-lock on older versions of Emacs.
Doom removes it (https://github.com/hlissner/doom-emacs/blob/develop/core/core-modules.el#L343-L345) and I do as well to make use-package highlighted the same as other macros (I have a number of small wrappers which set some defaults and pass through all other forms for convenience).
=> Remove use-package-font-lock-keywords

use-package-core.el
```
■  Warning (comp): use-package-core.el:907:2: Warning: docstring has
wrong usage of unescaped single quotes (use \= or different quoting)
■  Warning (comp): use-package-core.el:930:2: Warning: docstring has
wrong usage of unescaped single quotes (use \= or different quoting)
```
To reproduce, have emacs built with native compilation and notice the compilation logs. You can then open a file and run `M-x emacs-lisp-native-compile-and-load` before and after the changes to see the warning is removed.
=> Fix emacs native compilation warning

.github/workflows/test.yml, Makefile.lisp, bind-key.el
I did not know bind-key was part of this repository, I thought it might be it's own separate package. Otherwise I would have made this change as part of #997 . The CI pipeline is updated now with newer emacs versions, and the compiler make target adds the extra flags/eval to ensure compilation fails if warnigns are present, to ensure this will not pop up again in the future.
To reproduce, have emacs built with native compilation and notice the
compilation logs. You can then open the offending file and run `M-x
emacs-lisp-native-compile-and-load` before and after the changes to see
the warning is removed.
```
■  Warning (comp): bind-key.el:150:2: Warning: docstring has wrong
usage of unescaped single quotes (use \= or different quoting)
```
=> Native compiler warnings part 2

README.md, use-package-core.el, use-package-tests.el
Add `:command*` keyword proposed at #851.  Special thanks to @aspiers.
This `:command*` is similar to `:command`, but it generate autoload
statement as no-interactive one.
=> Add :autoload keyword

use-package-core.el, use-package-tests.el
For reference, each time I press the "apply and save" button when I use Custom, my custom file stores not only the settings I've made but each face specified with the `:custom-face` section in my `use-package` declarations. This PR fixes it, as suggested in #934.
=> fix #934: use face-spec-set instead of custom-set-faces

README.md, use-package-core.el, use-package-tests.el, use-package.el
This allows passing the `spec-type` argument to `face-spec-set`. Fixes #1008
=> fix #1008: allow passing the SPEC-TYPE argument via :custom-face

README.md, use-package.texi
This changes `README.md` to recommend GNU ELPA over the one in MELPA.
=> Recommend GNU ELPA over MELPA

.elpaignore
We generally prefer not to include the `LICENSE` file in the GNU ELPA tarball, as it contributes to the file size for little benefit. We also no longer need to ignore `doc/`.
=> Ignore LICENSE in .elpaignore

bind-chord.el, bind-key.el, use-package-bind-key.el, use-package-chords-tests.el, use-package-chords.el, use-package-core.el, use-package-delight.el, use-package-diminish.el, use-package-ensure-system-package.el, use-package-ensure.el, use-package-jump.el, use-package-lint.el, use-package-tests.el, use-package.el
This fixes the GPLv3 license statement to use the new format (with a URL instead of a postal address). It also removes some redundant headers that are only needed in the main file of a package.
=> Fix some file headers

.dir-locals.el, .gitignore, bind-key.el, use-package-chords-tests.el, use-package-core.el, use-package-tests.el
This replaces some local variables with a `.dir-locals.el` file using some of the same customizations as in the main Emacs repository.
=> Add .dir-locals.el

bind-chord.el, bind-key.el, use-package.el
The `bind-key.el` and `bind-chord.el` were missing the `Package-Requires` header.
Also add in a known keyword from `finder-known-keywords` while we're at it.
These issues were found using `package-lint`.
=> Add package requires for bind-key.el and bind-chord.el

use-package-core.el
We are still lacking a copyright assignment for @matzebond, which is blocking the merge of `use-package` into Emacs. The only way forward if we want `use-package` in Emacs 29 is to revert this commit for now, and re-merge it once the copyright assignment is done. See issue #787 and #282.
@jwiegley What do you think?
This reverts commit 2808c8466fcce62cc96ae159d96d8205e78c4053.
=> Revert "Add: 'local' keyword" for lack of copyright assignment

use-package-tests.el
We are still lacking a copyright assignment for @jjlee, which is blocking the merge of `use-package` into Emacs. If we remove these tests, the total number of lines added by him will be under the limit, and we can merge this. See issue #840 and #282.
I have asked @jjlee to sign the papers, and once that is done we can add the tests again (probably to the main Emacs repository).
@jwiegley What do you think?
=> Remove tests lacking a copyright assignment for now

README.md, bind-key.el, use-package-bind-key.el, use-package-core.el, use-package-tests.el, use-package.texi
As pointed out in #967, `:bind` does currently not allow defining a key sequence using a cons – `(STRING . DEFN)` – as definition. Consequently, it is not possible to provide a custom description of the command, which e.g. the `which-key` package uses in its hints. This changeset is intended to enable such definitions.
I am new to both Emacs Lisp and the `use-package` code, so the current changes are probably best considered a proof of concept; I expect several changes need be made before merging. I would be grateful for suggestions on how to improve the implementation to the point where it can be merged.
- https://github.com/emacs-mirror/emacs/compare/master...joelpet:emacs:use-package-bind-desc-cons
=> Allow defining a key sequence using a cons with `:bind`
